TravelBlogCapstone.Web/Controllers/ApiControllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Microsoft.AspNet.Identity;
using TravelBlogCapstone.BLL;
using TravelBlogCapstone.Data.DapperRepositories;
using TravelBlogCapstone.Models;

namespace TravelBlogCapstone.Web.Controllers.ApiControllers
{
    [Authorize(Roles = "Admin,Employee")]
    public class EmployeeController : ApiController
    {
        EmployeeManager employeeMan = new EmployeeManager();

        [ActionName("GetCategories")]
        public List<Category> Get()
        {
            return employeeMan.GetAllCategories();
        }

        [ActionName("GetUserPostsIndex")]
        public List<Post> GetUserPostsIndex()
        {
            return employeeMan.GetAllUserPostsIndex(User.Identity.GetUserId());
        }

        [ActionName("GetApprovedPosts")]
        public List<Post> GetApprovedPosts()
        {
            return employeeMan.GetAllApprovedPost().Where(p => p.UserId == User.Identity.GetUserId()).ToList();
        }

    
        [ActionName("RemovePost")]
        [HttpPut]
        public HttpResponseMessage RemovePost(string id)
        {
            try
            {
                employeeMan.DeletePost(int.Parse(id));
                return Request.CreateResponse(HttpStatusCode.OK);
            }
            catch(Exception ex)
            {
                return Request.CreateResponse(HttpStatusCode.Conflict);
            }
        }

        public HttpResponseMessage Post(Post newPost)
        {
            try
            {
                employeeMan.CreateNewPost(newPost);
            }
            catch(Exception ex)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
            return Request.CreateResponse(HttpStatusCode.OK);
        }

    }
}

TravelBlogCapstone.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using TravelBlogCapstone.BLL;
using TravelBlogCapstone.Models;
using TravelBlogCapstone.Web.Models;

namespace TravelBlogCapstone.Web.Controllers
{
    [Authorize(Roles = "Admin,Employee")]
    public class EmployeeController : ApplicationBaseController
    {
        HomeManager manager = new HomeManager();
        EmployeeManager eManager = new EmployeeManager();

        // GET: Employee

        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult CreatePost()
        {

            Post newPost = new Post();
            newPost.UserId = User.Identity.GetUserId();
            return View(newPost);
        }

        public ActionResult UpdatePost(int id)
        {
            var post = manager.GetPost(id);
            var model = new EditPostVM();
            model.Post = post;
            

            var categories = eManager.GetAllCategories();
            model.SetCategoryList(categories, post.CategoriesId);
            model.SetStatusList();

            return View(model);
        }

        public ActionResult EmployeeViewPosts()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult UpdatePost(EditPostVM model)
        {

            if (ModelState.IsValid)
            {
                //comma separated list of tags
                var tags = Request["tagsArray"];

                var post = new Post();

                post = model.Post;
                post.TagsName = tags.Split(',').ToList();
                post.CategoriesId = model.CategoryIds;
                


                eManager.UpdatePost(post, model.StatusId);
                //call manager

                return RedirectToAction("Index");
            }

            var postInfo = manager.GetPost(model.Post.Id);
            model.Post = postInfo;

            var categories = eManager.GetAllCategories();
            model.SetCategoryList(categories, postInfo.CategoriesId);
            model.SetStatusList();

            return View(model);
        }

    }
}

TravelBlogCapstone.Web/Views/Employee/CreatePost.cshtml
@model TravelBlogCapstone.Models.Post
@{
    ViewBag.Title = "CreatePost";
}

<script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
<link href="~/Styles/createPostStyles.css" rel="stylesheet" />
<link href="~/Scripts/bootstrap-tagmanager.css" rel="stylesheet" />
<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        file_browser_callback: function(field_name, url, type, win) {
            win.document.getElementById(field_name).value = 'my browser value';
        },
        theme_advanced_resizing: true,
        theme_advanced_resizing_use_cookie: false,
        width: '100%',
        resize: 'vertical',
        theme: 'modern',
        plugins: [
            'advlist autolink autoresize lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
        ],
        toolbar1:
            'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
            '//www.tinymce.com/css/codepen.min.css'
        ]
    });
</script>

@if (Model.Remark != null)
{
    <div id="remarks">
        @Model.Remark
    </div>
}
<form method="post" id="createPostForm">
    @Html.HiddenFor(m=>m.UserId)
    <div class="row">
        <div class="col-sm-7" style="padding: 0px;">
            <input type="text" id="postTitle" name="postTitleEntry" style="width: 100%" placeholder="Title"/>
        </div>
        <div style="padding: 0px; float: right;">
            <select id="submissionOptions">
            </select>
            <input id="submitPost" type="submit" class="btn btn-primary btn-lg outline"/>
        </div>
    </div>
    <br/>
    <div class="row">
        <div>
            <textarea></textarea>
        </div>
    </div>
    <br/>
    <div class="row">
        <div>
            <input type="text" id="tags" name="tags" placeholder="Tags" class="tm-input"/>
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-sm-3 col-sm-offset-2">
            <p>Post Date:</p>
        </div>
        <div class="col-sm-3">
            <p>Categories:</p>
        </div>
        <div class="col-sm-3">
            <p>Expire Date:</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 col-sm-offset-2">
            <input type="date" id="publishDate" name="publishDateEntry"/>
        </div>
        <div class="col-sm-3">
            <select multiple id="categories" name="categoryList">
            </select>
        </div>
        <div class="col-sm-3">
            <input type="date" id="expireDate" name="expireDateEntry"/>
        </div>
        @*<div id="prefetch">
            <input class="typeahead" type="text" placeholder="Countries">
        </div>*@
    </div>
</form>

@section scripts{
    <script src="~/Scripts/scripts/loadCreatePost.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/scripts/jquery-validate-defaults.js"></script>
    <script src="~/Scripts/scripts/CreatePostValidate.js"></script>
    <script src="~/Scripts/scripts/savePost.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
   
    
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="~/Scripts/typeahead.js"></script>
    
    <script src="~/Scripts/jquery.tagsmanager.js"></script>
       
    <script>
        $(document)
            .ready(function() {
                $('<option value="4">Save Draft</option>').appendTo($('#submissionOptions'));
                $('<option value="2">Send for Approval</option>').appendTo($('#submissionOptions'));


                var countries = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.whitespace,
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    // url points to a json file that contains an array of country names, see
                    // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
                    prefetch: '../api/Post/GetTags'
                });


                //countries.initialize();

                var tagApi = $(".tm-input").tagsManager({
                    hiddenTagListName: 'tagsArray',
                    delimiters: [9, 13, 44]
                });
                $(".tm-input").typeahead(null, {
                    name: 'countries',
                    source: countries.ttAdapter()
                }).on('typeahead:selected', function (e, d) {
                    tagApi.tagsManager("pushTag", d.name);

                });

                jQuery(".tm-input").on('tm:pushed', function (e, tag) {
                    jQuery("#tags").val("");
                    jQuery(".tt-suggestion").val("");
                    jQuery(".tt-menu").hide();
                    $('.tm-input').typeahead('setQuery', '');
                   
                });


                ////$(".tm-input").tagsManager({
                ////    hiddenTagListName: 'tagsArray',
                ////    delimiters: [9, 13, 44]
                ////});

                //jQuery(".tm-input").typeahead(null, {
                //    name: 'tags',
                //    displayKey: 'TagName',
                //    source: tags.ttAdapter()
                //}).on('typeahead:selected', function (e, d) {
                //    tagApi.tagsManager("pushTag", d.name);
                //});

                //$(".tm-input").tagsManager({
                //    hiddenTagListName: 'tagsArray',
                //    delimiters: [9, 13, 44]
                //});

               
                // passing in `null` for the `options` arguments will result in the default
                // options being used
                //$('#prefetch .typeahead').typeahead(null, {
                //    name: 'countries',
                //    //source: countries
                //    source: countries.ttAdapter()
                //});


            });
    </script>
    
}

TravelBlogCapstone.Web/Views/Employee/EmployeeViewPosts.cshtml
@{
    ViewBag.Title = "My Posts";
}

<script src="~/Scripts/plugins/bootstrap/modal.js"></script>

<h2>@ViewBag.Title</h2>
<hr />
<div class="row">
    <div class="col-xs-12">
        @Html.Partial("_ViewPostModal")
    </div>
</div>

<div class="alert alert-success" style="display: none;"></div>
<div class="alert alert-danger" style="display: none;"></div>

<div class="row">
    <div class="col-sm-7">
        <table class="table table-responsive" id="approvedPosts">
            <thead>
                <tr>
                    <th style="width: 25%">Published?</th>
                    <th style="width: 60%">Post</th>
                    <th style="width: 15%">Edit</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>

        <div class="text-center">
            <button class="btn btn-primary" id="showAllButton" style="display: none">Show All</button>
        </div>

    </div>

</div>

@section scripts{
<script src="~/Scripts/plugins/bootstrap/modal.js"></script>
    <script src="~/Scripts/moment.min.js"></script>
    <script src="~/Scripts/scripts/EmployeeViewPosts.js"></script>
}

TravelBlogCapstone.Web/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Employee Home";
}

@section styles{
    <link href="~/Styles/adminIndex.css" rel="stylesheet" />
}
<h2>@ViewBag.Title</h2>
<hr />

<div class="alert alert-success" style="display: none;"></div>
<div class="alert alert-danger" style="display: none;"></div>

<div class="row">
    <div class="col-xs-12 col-sm-4">
        @Html.ActionLink("Create Post", "CreatePost", "Employee", null, new {@class = "btn btn-primary btn-lg outline menuButton"})
        <br/>
        @Html.ActionLink("View Posts", "EmployeeViewPosts", "Employee", null, new {@class = "btn btn-primary btn-lg outline menuButton"})
        <br/>

    </div>
    <div class="col-xs-12 col-sm-8">
        <table class="table table-responsive" id="pendingPosts">
            <thead>
            <tr>
                <th>Status</th>
                <th>Post</th>
                <th>Delete</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>


        <div class="text-center">
            <button class="btn btn-primary" id="showAllButton" style="display: none">Show All</button>
        </div>

    </div>

</div>

@section scripts{
    <script src="~/Scripts/scripts/EmployeeIndex.js"></script>
}

TravelBlogCapstone.Web/Views/Employee/UpdatePost.cshtml
@model TravelBlogCapstone.Web.Models.EditPostVM
@{
    ViewBag.Title = "Update Post";
}

<script src="https://cdn.tinymce.com/4/tinymce.min.js"></script>
<link href="~/Styles/createPostStyles.css" rel="stylesheet" />
<link href="~/Scripts/bootstrap-tagmanager.css" rel="stylesheet" />
<script type="text/javascript">
    tinymce.init({
        selector: 'textarea',
        file_browser_callback: function(field_name, url, type, win) {
            win.document.getElementById(field_name).value = 'my browser value';
        },
        theme_advanced_resizing: true,
        theme_advanced_resizing_use_cookie: false,
        width: '100%',
        resize: 'vertical',
        theme: 'modern',
        plugins: [
            'advlist autolink autoresize lists link image charmap print preview hr anchor pagebreak',
            'searchreplace wordcount visualblocks visualchars code fullscreen',
            'insertdatetime media nonbreaking save table contextmenu directionality',
            'emoticons template paste textcolor colorpicker textpattern imagetools'
        ],
        toolbar1:
            'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
        toolbar2: 'print preview media | forecolor backcolor emoticons',
        image_advtab: true,
        templates: [
            { title: 'Test template 1', content: 'Test 1' },
            { title: 'Test template 2', content: 'Test 2' }
        ],
        content_css: [
            '//fast.fonts.net/cssapi/e6dc9b99-64fe-4292-ad98-6974f93cd2a2.css',
            '//www.tinymce.com/css/codepen.min.css'
        ]
    });
</script>

@if (Model.Post.Remark != null)
{
    <div id="remarks">
        Remark: @Model.Post.Remark
        <br/>
        <br/>
    </div>
}
@Html.ValidationSummary()
<form method="post" id="createPostForm">
        @Html.HiddenFor(m=>m.Post.Id)
        @Html.HiddenFor(m => m.Post.StatusId)
        @Html.HiddenFor(m => m.Post.UserId)
    <div class="row">
        <div class="col-sm-7" style="padding: 0px;">
            @Html.TextBoxFor(m=>m.Post.Title, new {style = "width: 100%"})
        </div>
        <div style="padding: 0px; float: right;">
            @Html.DropDownListFor(m=>m.StatusId, Model.StatusList)
            <input id="submitPost" type="submit" value="Update" class="btn btn-primary btn-lg outline" />
        </div>
    </div>
    <br />
    <div class="row">
        <div>
            @Html.TextAreaFor(m=>m.Post.PostContent)
        </div>
    </div>
    <br />
    <div class="row">
        <div>
            <input type="text" id="tags" name="tags" placeholder="Tags" class="tm-input" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-3 col-sm-offset-2">
            <p>Post Date:</p>
        </div>
        <div class="col-sm-3">
            <p>Categories:</p>
        </div>
        <div class="col-sm-3">
            <p>Expire Date:</p>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3 col-sm-offset-2">
            @Html.EditorFor(m=>m.Post.PublishedDate)
        </div>
        <div class="col-sm-3">
           @Html.ListBoxFor(m=>m.CategoryIds, Model.Categories)
        </div>
        <div class="col-sm-3">
            @Html.EditorFor(m => m.Post.ExpiredDate)
        </div>
    </div>
</form>

@section scripts{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/scripts/jquery-validate-defaults.js"></script>
    <script src="~/Scripts/scripts/CreatePostValidate.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>
    <script src="~/Scripts/typeahead.js"></script>

    <script src="~/Scripts/jquery.tagsmanager.js"></script>
    <script>
        $(document)
            .ready(function () {
                $('<option value="4">Save Draft</option>').appendTo($('#submissionOptions'));
                $('<option value="2">Send for Approval</option>').appendTo($('#submissionOptions'));


                var countries = new Bloodhound({
                    datumTokenizer: Bloodhound.tokenizers.whitespace,
                    queryTokenizer: Bloodhound.tokenizers.whitespace,
                    // url points to a json file that contains an array of country names, see
                    // https://github.com/twitter/typeahead.js/blob/gh-pages/data/countries.json
                    prefetch: '../api/Post/GetTags'
                });

                var tagApi = $(".tm-input").tagsManager({
                    prefilled: [
                      @Html.Raw(String.Join(", ", (Model.Post.Tags.Select(t => string.Format("\"{0}\"", t.TagName)))))
                    ],

                    hiddenTagListName: 'tagsArray',
                    delimiters: [9, 13, 44]
                });
                $(".tm-input").typeahead(null, {
                    name: 'countries',
                    source: countries.ttAdapter()
                }).on('typeahead:selected', function (e, d) {
                    tagApi.tagsManager("pushTag", d.name);

                });

                jQuery(".tm-input").on('tm:pushed', function (e, tag) {
                    jQuery("#tags").val("");
                    jQuery(".tt-suggestion").val("");
                    jQuery(".tt-menu").hide();
                    $('.tm-input').typeahead('setQuery', '');

                });
                

                @*$(".tm-input").tagsManager({
                    prefilled: [
                      @Html.Raw(String.Join(", ", (Model.Post.Tags.Select(t => string.Format("\"{0}\"", t.TagName)))))
                    ],
                    hiddenTagListName: 'tagsArray',
                    delimiters: [9, 13, 44]
                });*@
            });
    </script>

}